version: "3"

services:
  labweb1:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
        - 8080
    environment:
      HTTP_PORT: 8080
      VIRTUAL_HOST: tun97.me
      LETSENCRYPT_HOST: tun97.me
      LETSENCRYPT_EMAIL: "kaito1477800@gmail.com"
    networks:
      service_network:

  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    container_name: nginx-proxy
    networks:
      service_network:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

networks:
  service_network:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  db_data: